### ISSUE TITLE
Claymores have no throwing animation

### ISSUE THREAD

**Issue by Iridar** [Musashi1584/RPGO#19]
Solution:
Give the claymore Game Archetype to Claymore item weapon: "WP_Claymore.WP_Claymore".

May also  need to set `FF_Grenade` fire animation, either for the ThrowClaymore ability, or set it for Claymore item the same way pistols set their triple shot animation for Fan Fire.

**Comment by ICiscoStu** [comment]
@Iridar can you give me some pointers on where to add this change? I'm fairly new at modding and the overhaul code is a little daunting...

I tried initially to add the change into X2TemplateHelper_RPGOverhaul::UpdateAnimations

but that did not work

**Comment by Iridar** [comment]
The correct place to address this would be OnPostTemplatesCreated, which RPGO already uses to do a lot of changes. You can read a bit more about using OPTC here: https://www.reddit.com/r/xcom2mods/wiki/wotc_modding/optc

And about weapon setup here: https://steamcommunity.com/sharedfiles/filedetails/?id=1689878874
