### ISSUE TITLE
Random Classes Improvements

### ISSUE THREAD

**Issue by Iridar** [Musashi1584/RPGO#48]
The randomization process needs to be improved to generate more functional classes. Some potential options:

1) Look at the **AbilityWeaponCategoryRestrictions** to make sure that all perks from the to-be-complementary spec can be used with either primary or secondary weapon categories granted by the primary or secondary spec.

2) Add a list of **Compatible Weapon Categories** to each spec, that will function alongside **Allowed Weapon Categories**.

Like, "in principle, this spec is intended to be used with these weapon categories, but it is also compatible with these weapon categories. And then we could also make a configurable array of equivalent weapon categories. For example, generally swords and combat knives are the same thing.

Same goes for rifles and SMGs (if someone is using a mod that makes an SMG a separate weapon cat)

This would let us use `bShoot` and friends only when a spec is truly compatible with any gun.

3) Some Secondary Specializations, like Ballistic Shields and Canisters are compatible only with specific primary weapon categories, so we should add a configurable array of those as well.

**Comment by ProfBadger** [comment]
So a very minor thing that I'm just going to bring up, sometimes for specialisations that are both primary and/or secondary, it can be a little difficult to figure out which slot it's working with? Stormrider is probably the one that I've seen the most,, but theoretically a lot of the sword or pistol specialisations can be unclear about which slot they're representing.

**Comment by Iridar** [comment]
> So a very minor thing that I'm just going to bring up, sometimes for specialisations that are both primary and/or secondary, it can be a little difficult to figure out which slot it's working with? Stormrider is probably the one that I've seen the most,, but theoretically a lot of the sword or pistol specialisations can be unclear about which slot they're representing.

You can see which spec is which in the lower left corner of the promotion screen.

If you're talking about specialization selection screen, specs are marked with [P] or [S], self explanatory.

**Comment by ProfBadger** [comment]
Maybe this is more for explicitly Random Class/Commander's Choice and I should bring it up over there.

**Comment by Iridar** [comment]
> Maybe this is more for explicitly Random Class/Commander's Choice and I should bring it up over there.

There's nothing to bring up, I already explained, specs are marked.

**Comment by Iridar** [comment]
Oh, one thing I forgot to mention is that Weapon Restrictions work differently with Commander's Choice / Spec Roulette. They don't split the specs in primary or secondary. So e.g. a Gunslinger spec will let you use pistols in both slots.

**Comment by ProfBadger** [comment]
Ah, I see. That's where I was confused.
