### ISSUE TITLE
Professional perk applies to non-overwatch shots

### ISSUE THREAD

**Issue by Iridar** [Musashi1584/RPGO#57]
As reported by Blaze: https://discordapp.com/channels/165245941664710656/383948341471346688/705887600929538140

I have experienced it previously myself as well. As a personal recommendation, I would suggest dropping XMB from this perk, and reimplementing it as a passive ability that applies a Persistent Effect with a GetAttackingDamageModifier hook to boost damage of reaction fire abilities.

**Comment by Musashi1584** [comment]
Since xyl seems currently active it might be good to bring this to his attention if it’s a issue with xmb

**Comment by Favid** [comment]
First thing I'd suggest trying is adding the default.ReactionFireCondition to AbilityTargetConditions instead of AbilityShooterConditions.
